#!/usr/bin/env bash
# Script to report information about server domains and their subdomains 

print_domain_subdomain() {
   local domain="$1"
   local subdomain="$2"

   local result
   result=$(dig +short "$subdomain.$domain")

   if [ -z "$result" ]; then
	   echo "Subdomain '$subdomain' not found for domain '$domain'."
	   return 1
    fi

    local record_type=$(dig +short -t "$subdomain" "$domain")
    echo "The subdomain '$subdomain' is a $record_type record and points to $result"
}

if [ "$#" -eq 2 ]; then
	print_domain_subdomain "$1" "$2"
else
	print_domain_subdomain "$1" "www"
	print_domain_subdomain "$1" "lb-01"
	print_domain_subdomain "$1" "web-01"
	print_domain_subdomain "$1" "web-02"
fi
