#!/usr/bin/env bash
# Script that transfers a file from client to server
#
# Check the number of parameter
if [ "$#" -lt 4 ]; then 
   echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
