#!/usr/bin/env bash
#Script that installs nginx on web server; Ngin should be listening on 80
#Update package index and install nginx with -y flag for automatic yes to prompts
sudo apt-get update
sudo apt-get install -y nginx 
sudo ufw allow "Nginx HTTP"
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
