#!/usr/bin/env bash
#Script that installs nginx on web server; Nginx should be listening port on 80
#Update package index and install nginx with -y flag for automatic yes to prompts


echo -e "Updating and installing Nginx./n"
sudo apt-get update -y -qq && \
	sudo apt-get install -y nginx 

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start
sudo ufw allow "Nginx HTTP"


sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx restart
