#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me is redirecting to another page# The redirection must be a "301 Move Permanently"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y 


echo -e "\nSetting up some minor stuff.\n"
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
ADD301_REDIRECT="location /redirect_me {
	return 301 https://twitter.com/Emmanue17280546;
}"

sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart

echo -e "\nCompleted.\n"
