#!/usr/bin/env bash
#This script configures Nginx to add a custom HTTP response header


set -euo pipefail


sudo apt-get update
sudo apt-get install -y nginx 
sudo tee /etc/nginx/sites-available/default >/dev/null <<'EOF'
server {
	listen 80 d_server;
	listen [::]:80 d_server;


	server_name_;


	location / {
		proxy_pass http:localhost:5000;
		proxy_set_header X-Served-By $HOSTNAME;
		proxy_http_version 1.1;
		proxy_set_header Upgrade \$http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host \$host;
		proxy_cache_bypass \$http_upgrade;
	}
}
EOF

sudo systemctl restart nginx 
