#!/usr/bin/env bash
# This module configures Nginx to add a costom HTTP response header

set -euo pipefail

sudo apt-get -y update
sudo apt-get install -y nginx 

HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By \"$HOST_NAME;\n"
if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
	sudo sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    REDIRECT="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.twitter.com/Khaya;\n\t}"
    sudo sed -i "42i $REDIRECT" /etc/nginx/sites-available/default
fi

if ! grep -q "error_page 404"  /etc/nginx/sites-available/default; then
	ERROR="\\\n\terror_page 404 /custom_404.html;"
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
	sudo sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

sudo service nginx restart

echo "Nginx configuration completed successfully."
