#!/usr/bin/env bash
#This script install and configure HAproxy on your lb-01 server.

set -euo pipefail

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8.*
apt-get update
apt-get install -y haproxy=1.8.*
load_balancer="
fronted http
	bind *:80
	mode http
	default_backend load_b

backend load_b 
	balance roundrobin
	server web-01 [100.25.182.120]-web-01:80 check
	server web-02 [54.160.104.49]-web-02:80 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" |sudo tee -a /etc/haproxy/haproxy.cfg

systemctl restart haproxy
