#!/usr/bin/env bash
# This script ensures that Nginx is running and listening on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
service nginx restart
