#!/usr/bin/env bash
# Script configures a server to listening on port 80 of all servers active IPv4 Ips

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
sudo service nginx restart
