#!/usr/bin/env bash
# This script ensures that Nginx is running and listening on port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop 2>&1 | grep -q "not running"
