#!/usr/bin/env bash
# This script displays messages when receiving signals


cleanup_and_exit()
{
	echo "Exiting..."
	rm -f /var/run/myscript.pid
	exit
}


trap 'echo "I hate the kill command"; clean_and_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup_and_exit' SIGQUIT

echo $$ > /var/run/myscript.pid


while true; do
	echo "To infinity and beyond"
	sleep 2
done
