#!/usr/bin/env bash
#This script manages my_process

PIDFILE=.var/run/my_process.pid


start()
{
	./manage_my_process &
	echo "$!" > "$PIDFILE"
}


stop()
{
	if [ -f "$PIDFILE" ]; then
		sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
	else
		echo "PID file $PIDFILE not found. Process my not be running."
	fi
}

case "$1" in
	start)
		start
		echo " my_process started"
		;;
	stop)
		stop
		echo "my_process stopped"
		;;
	restart)
		stop
		start
		echo "my_process restarted"
		;;
	*)
		echo "Usege: $0 {start|stop|restart}"
		exit 1
		;;
	esac


	exit 0
