#!/usr/bin/env bash
# A script that loops through 1 to 10 using while


j=1

while [ $j -le 11 ]
do
	if [ i = 4 ]
	then
		echo "bad luck"
	elif [ $j = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((j++))
done
