#!/usr/bin/env bash

#Displays Best School 10 times


j=1
while [ $j -lt 11]
do
	if [ i = 4 ]
	then
		echo "bad luck"
	elif [ $j = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let j+=1
done
