#!/usr/bin/env bash
# Displays the content of the current directorY in a list format
# Where only part of the name after the first dash is displayed

for file in *; do
	if [[ $file =~ ^[^-]*- -(.*) ]]; then
		echo "${BASH_REMATCH[1]}"
	fi
done
