#!/usr/bin/env bash
# This script displays content of the current directory 
# Only the part of the name after the first dash

for f in *
do
	if [[ $f != .* ]]; then
		name="${f#*-}"
		echo "$name"
	fi
done
