#!/usr/bin/env bash
# This script that configures an Ubuntu server with the below requirements.

if [ "$(id -u)" -ne 0 ]; then
	echo "This script must be run as root " >&2
	exit 1
fi

new_localhost='127.0.0.2'
new_facebook='8.8.8.8'

cp /etc/hosts ~/hosts.new

sed -i 's/^127\.0\.0\.1.*/127.0.0.1 localhost/' /etc/hosts
echo "$new_localhost localhost" >> /etc/hosts

sed -i '/^$new_localhost/a$new_facebook facebook.com' /etc/hosts

sudo cp -f ~/hosts.new /etc/hosts
