#!/usr/bin/env bash
# This script that configures an Ubuntu server with the below requirements.

sudo cp /etc/hosts /etc/hosts.backup

sudo sed -i 's/^127\.0\.0\.1\b/127.0.0.2/' /etc/hosts

sudo sed -i '/^127\.0\.0\.2\b/a 8.8.8.8 facebook.com' /etc/hosts
