#!/usr/bin/env bash
# This script that configures an Ubuntu server with the below requirements.
if [ "$(id -u)" -ne 0 ]; then
	echo "This script must be run as root " >&2
	exit 1
fi

cp /etc/hosts ~/hosts.new

sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

sed -i '2i8.8.8.8 facebook.com' ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts
