#!/usr/bin/env bash
pkill apache2
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx
nginx -g 'daemon off;'
