#!/usr/bin/env bash

# Stop Apaches2 if running
pkill apache2

@ Change ownership and permissions of nginx.conf
chwn nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf

# Change Nginx configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Restart Nginx service
sudo -unginx service nginx restart
