#!/usr/bin/env bash
# ssh client configuration

host *
      PasswordAuthentication no
      IdentityFile ~/.ssh/school
      SendEnv LANG LC_*
      HashKnowHosts yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no
      
